- name: Install afni dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    autoclean: yes
    autoremove: yes
  vars:
    packages:
    - tcsh
    - xfonts-base
    - gsl-bin
    - netpbm
    - libjpeg62
    - xvfb
    - libglu1-mesa-dev
    - libglw1-mesa
    - libxm4
    - libcurl4-openssl-dev
    - libxml2-dev
    - libssl-dev
    - libgfortran4

#Fix afni being built against a different version of gsl
#https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu20.html
- name: fix libgsl
  file:
    src: /usr/lib/x86_64-linux-gnu/libgsl.so.23
    dest: /usr/lib/x86_64-linux-gnu/libgsl.so.19
    state: link

- name: download afni installer
  get_url:
    url: https://afni.nimh.nih.gov/pub/dist/bin/linux_ubuntu_16_64/@update.afni.binaries
    dest: /tmp/@update.afni.binaries

- name: install afni
  shell: tcsh /tmp/@update.afni.binaries -package linux_ubuntu_16_64 -apsearch yes -bindir /opt/quarantine/afni
  args:
    creates: /opt/quarantine/afni

- name: add afni to path
  lineinfile:
    path: /etc/profile.d/99afni.sh
    line: "export PATH=/opt/quarantine/afni${PATH:+:$PATH}"
    create: yes
