- name: download fsl
  get_url:
    url: https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py
    dest: /tmp/fslinstaller.py

- name: install fsl
  shell: python /tmp/fslinstaller.py -d /opt/quarantine/fsl -p -q
  args:
    creates: /opt/quarantine/fsl

- name: setup fsl
  lineinfile:
    path: /etc/profile.d/99fsl.sh
    line: "export FSLDIR=/opt/quarantine/fsl && export PATH=/opt/quarantine/fsl/bin${PATH:+:$PATH} && . ${FSLDIR}/etc/fslconf/fsl.sh"
    create: yes
