- apt: upgrade=dist update_cache=yes

- name: accept mscorefonts
  debconf: name='ttf-mscorefonts-installer' question='msttcorefonts/accepted-mscorefonts-eula' value='true' vtype='select'

- name: Install Common APT Packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    autoclean: yes
    autoremove: yes
  vars:
    packages:
    - ncdu
    - htop
    - iotop
    - xauth
    - landscape-common
    - tmux
    - screen
    - imagemagick
    - exfat-utils
    - ntfs-3g
    - dosfstools
    - xfsprogs
    - reiserfsprogs
    - reiser4progs
    - dmraid
    - dmsetup
    - kpartx
    - cryptsetup
    - openssh-server
    - parallel
    - quota
    - nmap
    - lrzip
    - p7zip-full
    - unace
    - unrar
    - zip
    - unzip
    - sharutils
    - rar
    - uudeview
    - mpack
    - arj
    - cabextract
    - gdebi-core
    - ansible
    - apparmor-profiles-extra
    - apparmor-profiles
    - smartmontools
    - squashfs-tools
    - links2
    - aptitude
    - tree
    - unattended-upgrades
    - nvme-cli
    - libpng12-0

- name: Install Development APT Packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    autoclean: yes
    autoremove: yes
  vars:
    packages:
    - vim
    - emacs
    - build-essential
    - source-highlight
    - cmake
    - cmake-curses-gui
    - kitware-archive-keyring
    - ninja-build
    - gcc
    - gfortran
    - default-jre
    - git
    - make

- name: Install workstation apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  vars:
    packages:
      - google-chrome-stable
      - libreoffice
      - inkscape
      - gimp
      - vlc
      - signal-desktop

- name: Install minimal texlive
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  vars:
    packages:
      - texlive-base
      - texlive-bibtex-extra
      - texlive-binaries
      - texlive-extra-utils
      - texlive-font-utils
      - texlive-fonts-extra
      - texlive-fonts-extra-links
      - texlive-fonts-recommended
      - texlive-formats-extra
      - texlive-games
      - texlive-humanities
      - texlive-lang-english
      - texlive-lang-french
      - texlive-lang-greek
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-luatex
      - texlive-metapost
      - texlive-music
      - texlive-pictures
      - texlive-plain-generic
      - texlive-pstricks
      - texlive-publishers
      - texlive-science
      - texlive-xetex
      - texlive-bibtex-extra
      - texlive-formats-extra
      - texlive-games
      - texlive-humanities
      - texlive-music
      - texlive-publishers
      - texlive-science

- name: Cleanup
  shell: apt-get clean
  args:
    warn: false

- name: install miscellaneous debs
  apt: deb={{ item }}
  with_items:
    - https://www.mendeley.com/repositories/ubuntu/stable/amd64/mendeleydesktop-latest
    - https://atom.io/download/deb
    - https://downloads.slack-edge.com/linux_releases/slack-desktop-4.4.2-amd64.deb
    - https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
  ignore_errors: yes
