# Generated by `make vm-up` — do not edit by hand.
# Group name must stay `workstations` (deploy.yml targets `hosts: workstations`).
[workstations]
@VMNAME@ ansible_host=@IP@

[workstations:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=@KEY@
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
ansible_become=true
