---

- name: Install software-properties-common for apt-add-repository
  ansible.builtin.apt:
    name: software-properties-common
    state: present
    update_cache: true

- name: add apptainer ppa
  ansible.builtin.apt_repository:
    repo: ppa:apptainer/ppa
    state: present
    update_cache: false

- name: Install apptainer dependencies
  ansible.builtin.apt:
    update_cache: true
    state: present
    autoclean: true
    autoremove: true
    pkg:
      - apptainer
