---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/quarantine/software/mrtrix3/{{ mrtrix3_dev_version }}

- name: Install mtrix3-dev dependencies
  ansible.builtin.apt:
    update_cache: true
    state: present
    autoclean: true
    autoremove: true
    pkg:
      - python3
      - libeigen3-dev
      - zlib1g-dev
      - libqt5opengl5-dev
      - libqt5svg5-dev
      - libgl1-mesa-dev
      - libfftw3-dev
      - libtiff5-dev
      - libpng-dev

- name: Git checkout mrtrix3-dev
  ansible.builtin.git:
    repo: https://github.com/MRtrix3/mrtrix3.git
    dest: /opt/quarantine/software/mrtrix3/{{ mrtrix3_dev_version }}/install
    #version: dev

- name: Build mrtrix3-dev
  shell: ./configure && ./build
  args:
    creates: /opt/quarantine/software/mrtrix3/{{ mrtrix3_dev_version }}/install/bin/mrview
    chdir: /opt/quarantine/software/mrtrix3/{{ mrtrix3_dev_version }}/install

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/mrtrix3/{{ mrtrix3_dev_version }}/module
  notify: link modules
